from pymongo.errors import DuplicateKeyError

from api.dto.user_auth_dto import UserAuthDto

from api.models.user import User

async def create_user(user_auth_dto: UserAuthDto):
    user = User(
        username=user_auth_dto.username,
        password=user_auth_dto.password
    )
    
    try:
        await user.insert()
    except DuplicateKeyError as dke:
        return {
        "message": "Nome de usu치rio j치 est치 em uso.",
    }
    
    return {
        "message": "Usu치rio criado com sucesso!",
    }